# Generated by Django 4.0.4 on 2022-04-18 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.todolistmodel')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
